---
# Vagrantfile settings
boxipaddress: "0.0.0.0"
boxname: "asterisk"
interface: "eth0"
organization: "Asterisk"
hosts_file: "/etc/hosts"

# Asterisk user and group
asterisk_user: "asterisk"
asterisk_group: "asterisk"

# Asterisk connection settings
asterisk_ip: "{{ boxipaddress }}"
asterisk_tcp_port: 5060
asterisk_udp_port: 5060
asterisk_tls_port: 5061
asterisk_transport: "tls,tcp,udp"
asterisk_encryption: "no"

# Asterisk sip settings
asterisk_realm: "realm"
asterisk_context: "internal"

# Asterisk users
asterisk_users:
- {
    id: "identifier",
    extension: 100,
    callerid: "CallerID",
    secret: "password",
    context: "{{ asterisk_context }}"
  }

